version: "2.2"
services:
  prometheus:
    container_name: "prometheus"
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - "55000:9090"
    volumes:
      - ./prometheus/alert.rules:/etc/prometheus/alert.rules
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus-data:/prometheus
  
  grafana:
    image: grafana/grafana
    container_name: "grafana"
    restart: unless-stopped
    ports:
      - "55001:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/log:/var/log/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_USERS_ALLOW_SIGN_UP=false
        #- GF_SECURITY_ADMIN_PASSWORD=""
        #- GF_SECURITY_ADMIN_USER=""

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: "cadvisor"
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080

  node-exporter:
    image: prom/node-exporter:latest
    container_name: "node_exporter"
    restart: unless-stopped
    expose:
      - 9100

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093

  calert:
    container_name: calert
    image: ghcr.io/mr-karan/calert:latest
    command:
      - "--config=./config.toml"
    volumes:
      - ./calert/config.toml:/app/config.toml
    restart: unless-stopped
    expose:
      - 6000
